/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CreditcoinBase",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.CreditcoinBase__factory>;
    getContractFactory(
      name: "Erc20",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Erc20__factory>;
    getContractFactory(
      name: "Erc20Plus",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Erc20Plus__factory>;
    getContractFactory(
      name: "GluwaCreditVestingToken",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.GluwaCreditVestingToken__factory>;
    getContractFactory(
      name: "Owned",
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<Contracts.Owned__factory>;

    getContractAt(
      name: "CreditcoinBase",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.CreditcoinBase>;
    getContractAt(
      name: "Erc20",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Erc20>;
    getContractAt(
      name: "Erc20Plus",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Erc20Plus>;
    getContractAt(
      name: "GluwaCreditVestingToken",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.GluwaCreditVestingToken>;
    getContractAt(
      name: "Owned",
      address: string,
      signer?: ethers.Signer,
    ): Promise<Contracts.Owned>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions,
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer,
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer,
    ): Promise<ethers.Contract>;
  }
}
