---
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - RUST_CLIPPY
  - SPELL_CSPELL
  # https://gluwa.atlassian.net/browse/CSUB-459
  - MARKDOWN_MARKDOWN_LINK_CHECK
  # https://gluwa.atlassian.net/browse/CSUB-460
  - REPOSITORY_TRIVY
JSON_JSONLINT_ARGUMENTS: --comments
