[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'node/rpc',
    'pallets/rewards',
    'pallets/difficulty',
    'pallets/creditcoin',
    'pallets/creditcoin/runtime-api',
    'pallets/task-scheduler',
    'runtime',
    "sha3pow",
    "primitives",
    "test/client",
]
