[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'node/rpc',
    'pallets/rewards',
    'pallets/difficulty',
    'pallets/creditcoin',
    'pallets/offchain-task-scheduler/runtime-api',
    'pallets/offchain-task-scheduler',
    'pallets/task-voting',
    'runtime',
    "sha3pow",
    "primitives",
    "test/client",
    "test/runtime-utils",
]

[workspace.package]
version = '2.211.2'
authors = ['Gluwa Inc.', 'Nathan Whitaker <nathan.whitaker@gluwa.com>']
edition = '2021'
license = 'Unlicense'
publish = false
repository = 'https://github.com/gluwa/creditcoin-substrate/'

[workspace.dependencies]
assert_matches = { version = "1.5.0" }
creditcoin-node-runtime = { version = "2.211.2", path = "runtime" }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-benchmarking-cli = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-executive = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-support = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-system = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-system-benchmarking = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
hex-literal = { version = "0.3.4" }
jsonrpc-core = { version = "18.0.0" }
log = { version = "0.4.17" }
pallet-balances = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-creditcoin = { version = "2.211.2", default-features = false, path = "pallets/creditcoin" }
pallet-difficulty = { version = "2.211.2", default-features = false, path = "pallets/difficulty" }
pallet-offchain-task-scheduler = { version = "0.1.0", default-features = false, path = "pallets/offchain-task-scheduler" }
pallet-randomness-collective-flip = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-rewards = { version = "2.211.2", default-features = false, path = "pallets/rewards" }
pallet-scheduler = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-sudo = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-task-voting = { version = "2.211.2", default-features = false, path = "pallets/task-voting" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc-runtime-api = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
parity-scale-codec = { version = "3.2.1", default-features = false, features = [
    "derive",
] }
primitives = { version = "2.211.2", default-features = false, path = "primitives" }
runtime-utils = { package = "test-runtime-utils", default-features = false, path = "test/runtime-utils" }
sc-basic-authorship = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-cli = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", features = [
    "wasmtime",
] }
sc-client-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-client-db = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", features = [
    "test-helpers",
] }
sc-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-pow = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-executor = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", features = [
    "wasmtime",
] }
sc-keystore = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-offchain = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-rpc = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-rpc-api = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-service = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", features = [
    "test-helpers",
    "wasmtime",
] }
sc-telemetry = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool-api = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
scale-info = { version = "2.3", default-features = false, features = [
    "derive",
] }
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-application-crypto = { version = "6.0.0", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-arithmetic = { version = "5.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-consensus-pow = { version = "0.10.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-core = { version = "6.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-inherents = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-io = { version = "6.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-keystore = { version = "0.12.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-offchain = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "6.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-runtime-interface = { version = "6.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-session = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-state-machine = { default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-std = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-timestamp = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "4.0.0-dev", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
sp-version = { version = "5.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
substrate-build-script-utils = { version = "3.0.0", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
substrate-frame-rpc-system = { version = "4.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
substrate-prometheus-endpoint = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
substrate-test-client = { version = "*", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
substrate-wasm-builder = { version = "5.0.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
task-scheduler-runtime-api = { version = "0.1.0", default-features = false, path = "pallets/offchain-task-scheduler/runtime-api" }
tracing = { version = "5.0.0", default-features = false, branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git", package = "sp-tracing" }
try-runtime-cli = { version = "0.10.0-dev", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
frame-try-runtime = { version = "0.10.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.32" }
sp-keyring = { version = "6.0.0", branch = "polkadot-v0.9.32", git = "https://github.com/paritytech/substrate.git" }
