[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/rewards',
    'pallets/difficulty',
    'pallets/creditcoin',
    'pallets/creditcoin/rpc',
    'runtime',
    "sha3pow",
    "primitives",
]
