---
version: "3.2"

services:
  dev:
    container_name: creditcoin-node
    image: paritytech/ci-linux:c4f0daf3-20220113
    working_dir: /var/www/creditcoin-node
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/creditcoin-node/.cargo
    volumes:
      - .:/var/www/creditcoin-node
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/creditcoin-node --dev --ws-external"
