parameters:
  release: true
  rust: stable # Could be [stable, beta, nightly]
  artifactName: target
  builds:
    - target: x86_64-unknown-linux-gnu
      name: Linux
      pre-steps: []
    - target: x86_64-pc-windows-msvc
      name: Windows
      pre-steps: []
    - target: aarch64-apple-darwin
      name: Apple
      pre-steps: []
    - target: x86_64-apple-darwin
      name: Apple_
      pre-steps: []

jobs:
- ${{ each build in parameters['builds'] }}:
  - ${{ if contains(build.target, 'linux') }}:
    - template: cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}" 
        job_pool:
          vmImage: ubuntu-latest
        release: ${{ parameters['release'] }}
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              TAG="$(git describe --tag)"
              echo "##vso[task.setvariable variable=tag]$TAG"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: artifacts.yml
            parameters:
              archiveType: tar
              compression: gz
              archiveName: "$(REPO_BASE_NAME)-v$(TAG)-${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}
              builder: ${{ build.target }}

  - ${{ if contains(build.target, 'apple') }}:
    - template: cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}"
        job_pool:
          vmImage: macOS-11
        release: ${{ parameters['release'] }} 
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              TAG="$(git describe --tag)"
              echo "##vso[task.setvariable variable=tag]$TAG"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: artifacts.yml
            parameters:
              archiveType: 7z
              archiveName: "$(REPO_BASE_NAME)-v$(TAG)-${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}
              builder: ${{ build.target }}

  - ${{ if contains(build.target, 'windows') }}:
    - template: cargo-build.yml
      parameters:
        rust: ${{ parameters['rust'] }}
        job_name: ${{ build.name }}
        job_displayName: "target ${{ build.target }}"
        job_pool:
          vmImage: windows-latest
        release: ${{ parameters['release'] }}
        target: "${{ build.target }}"
        job_pre-steps: ${{ build['pre-steps'] }}
        job_post-steps:
          - bash: |
              REPO_BASE_NAME="$(basename $(Build.Repository.Name))"
              TAG="$(git describe --tag)"
              echo "##vso[task.setvariable variable=tag]$TAG"
              echo "##vso[task.setvariable variable=repo_base_name]$REPO_BASE_NAME"
          - template: artifacts.yml
            parameters:
              archiveName: "$(REPO_BASE_NAME)-v$(TAG)-${{ build.target }}"
              artifactName: ${{ parameters['artifactName'] }}
              builder: ${{ build.target }}
