# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
    - ci-linux/*

pr: none

##Use self hosted build server. Resource ID: resourceGroups/devcommon/providers/Microsoft.Compute/virtualMachines/Ubuntu16BuildServer
pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  dockerfilePath: '../ci-linux/ci-linux.Dockerfile'
  registryName: 'gluwa/ci-linux'
  DOCKER_BUILDKIT: 1

stages:
- stage: Build_CI_Image
  displayName: BuildnPush CI Image
  jobs:
  - job: Build_CI
    displayName: Build_CI_Image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub - mrausnadian'
        repository: 'gluwa/ci-linux'
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          production
