
//! Autogenerated weights for `crate`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-03, STEPS: `2`, REPEAT: `1`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `crb307-n2`, CPU: `Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/creditcoin-node
// benchmark
// pallet
// --chain
// dev
// --steps=2
// --repeat=1
// --pallet
// crate
// --extrinsic=*
// --execution
// wasm
// --wasm-execution=compiled
// --heap-pages=10000
// --output
// ./pallets/offchain-task-scheduler/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `crate`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: TaskScheduler PendingTasks (r:1024 w:1024)
	/// Proof: TaskScheduler PendingTasks (max_values: None, max_size: Some(1276), added: 3751, mode: MaxEncodedLen)
	/// The range of component `t` is `[0, 1024]`.
	fn on_initialize(_t: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42 + t * (69 ±0)`
		//  Estimated: `3842014`
		// Minimum execution time: 15_001_000 picoseconds.
		Weight::from_parts(1_789_402_000, 0)
			.saturating_add(Weight::from_parts(0, 3842014))
			.saturating_add(T::DbWeight::get().reads(1024))
			.saturating_add(T::DbWeight::get().writes(1024))
	}
}
