---
name: Creditcoin-CLI CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main, testnet, dev]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    name: unit-tests

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn

      - name: Run tools
        run: |
          pushd creditcoin-js/ && yarn install && yarn pack && popd
          pushd scripts/cc-cli

          yarn upgrade 'creditcoin-js'
          yarn test
          popd
