---
name: Deploy docs
on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions: read-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    # checkov:skip=CKV2_GHA_1:We need this for the git push command below
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install mdbook
        uses: taiki-e/install-action@v2.33.11
        with:
          tool: mdbook,mdbook-mermaid
      - name: Deploy GitHub Pages
        run: |
          # This assumes your book is in the root of your repository.
          # Just add a `cd` here if you need to change to another directory.
          cd docs/dev-guide
          mdbook build
          git worktree add gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf ./*
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force --set-upstream origin gh-pages
