name: Check Runtime and Extrinsics

# This CI checks for changes in Creditcoin runtime and extrinsic ordering

# Controls when the action will run.
on:
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_extrinsics:
    name: Extrinsics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install --ignore-scripts -g @polkadot/metadata-cmp

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl protobuf-compiler

      - name: Configure rustc version
        run: |
          source ci/env
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> $GITHUB_ENV

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run Extrinsics Ordering
        shell: bash
        run: |
          ./scripts/check-extrinsics.sh

      #Upload logs if nodes are not connecting.
      #head-node.log and release-node.log are created in ./scripts/check-extrinsics.sh
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 'extrinsic-logs'
          path: |
            head-node.log
            release-node.log
