name: Check Runtime and Extrinsics

# This CI checks for changes in Creditcoin runtime and extrinsic ordering

# Controls when the action will run.
on:
  pull_request:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_extrinsics:
    name: Extrinsics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install --ignore-scripts -g @polkadot/metadata-cmp

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-21
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run Extrinsics Ordering
        shell: bash
        run: |
          ./scripts/extrinsic_check.sh

      #Upload logs if nodes are not connecting.
      #head-node.log and release-node.log are created in ./scripts/extrinsic_check.sh
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: 'extrinsic-logs'
          path: |
            head-node.log
            release-node.log

  check_runtime:
    name: Runtime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Clone Substrate Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100
          repository: gluwa/substrate
          path: substrate

      - name: Runtime Check
        shell: bash
        run: |
          ./scripts/runtime_check.sh
