---
name: Runtime Upgrade

on:
  pull_request:
    branches: [main, testnet]

permissions: read-all

env:
  RUNNER_VM_NAME: "github-runner-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  RESOURCE_GROUP: "github-runner-$GITHUB_RUN_ID-attempt-$GITHUB_RUN_ATTEMPT"
  AZ_LOCATION: "westus3"

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set-Up
        run: |
          sudo apt-get update
          sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl protobuf-compiler

      - name: Configure rustc version
        run: |
          source ci/env
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2

      - name: Build SUT
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features try-runtime

      - name: Upload creditcoin-node binary
        uses: actions/upload-artifact@v3
        with:
          name: creditcoin-node
          path: target/release/creditcoin-node

      - name: Upload WASM runtime
        uses: actions/upload-artifact@v3
        with:
          name: creditcoin_node_runtime.compact.compressed.wasm
          path: target/release/wbuild/creditcoin-node-runtime/creditcoin_node_runtime.compact.compressed.wasm

  fork-creditcoin:
    needs:
      - setup
      - deploy-github-runner
    runs-on:
      [self-hosted, "${{ needs.deploy-github-runner.outputs.runner_vm_name }}"]

    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt install -y unzip jq

      - name: Testnet ENV
        id: testnet-env
        if: github.base_ref == 'testnet'
        run: |
          echo "target_chain=test" >> "$GITHUB_OUTPUT"
          echo "rpc_url=wss://rpc.testnet.creditcoin.network:443/ws" >> "$GITHUB_OUTPUT"
          echo "https_rpc_url=https://rpc.testnet.creditcoin.network/rpc" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(./scripts/extract-release-tag.sh "testnet")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=creditcoin-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"

      - name: Mainnet ENV
        id: mainnet-env
        if: github.base_ref == 'main'
        run: |
          echo "target_chain=main" >> "$GITHUB_OUTPUT"
          echo "rpc_url=wss://rpc.mainnet.creditcoin.network:443/ws" >> "$GITHUB_OUTPUT"
          echo "https_rpc_url=https://rpc.mainnet.creditcoin.network/rpc" >> "$GITHUB_OUTPUT"
          RELEASE_TAG=$(./scripts/extract-release-tag.sh "runtime")
          echo "release_tag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"
          echo "artifact_name=creditcoin-$RELEASE_TAG-$(uname -m)-unknown-linux-gnu.zip" >> "$GITHUB_OUTPUT"

      - name: Download creditcoin-node for release ${{ steps.testnet-env.outputs.release_tag || steps.mainnet-env.outputs.release_tag }}
        uses: i3h/download-release-asset@v1
        with:
          owner: gluwa
          repo: creditcoin
          tag: ${{ steps.testnet-env.outputs.release_tag || steps.mainnet-env.outputs.release_tag }}
          file: ${{ steps.testnet-env.outputs.artifact_name || steps.mainnet-env.outputs.artifact_name }}

      - name: Download creditcoin-fork
        uses: i3h/download-release-asset@v1
        with:
          owner: gluwa
          repo: creditcoin-fork
          tag: latest
          file: creditcoin-fork

      - name: Create fork
        run: |
          # store info about the last finalized block before the fork
          # WARNING: using getBlockHash() instead of getFinalizedBlock() b/c PoW doesn't have finalization
          LAST_BLOCK=$(curl --silent -H "Content-Type: application/json" \
               -d '{"id": 1, "jsonrpc": "2.0", "method": "chain_getBlockHash", "params": [] }' \
               ${{ env.HTTPS_RPC_URL }} | jq -r .result)
          echo "$LAST_BLOCK" > last-block.hash

          curl --silent -H "Content-Type: application/json" \
               -d "{\"id\": 1, \"jsonrpc\": \"2.0\", \"method\": \"chain_getBlock\", \"params\": [\"$LAST_BLOCK\"] }" \
               ${{ env.HTTPS_RPC_URL }} | jq -r .result > last-block.json

          sudo apt-get update
          sudo apt install -y unzip

          unzip creditcoin-*-unknown-linux-gnu.zip
          chmod a+x ./creditcoin-node
          chmod a+x ./creditcoin-fork
          ./creditcoin-fork --bin ./creditcoin-node --orig ${{ env.TARGET_CHAIN }} --base dev --name Development \
                            -o creditcoin-fork.json --rpc ${{ env.RPC_URL }}
        env:
          TARGET_CHAIN: ${{ steps.testnet-env.outputs.target_chain || steps.mainnet-env.outputs.target_chain }}
          RPC_URL: ${{ steps.testnet-env.outputs.rpc_url || steps.mainnet-env.outputs.rpc_url }}
          HTTPS_RPC_URL: ${{ steps.testnet-env.outputs.https_rpc_url || steps.mainnet-env.outputs.https_rpc_url }}

      - name: Upload creditcoin-fork.json
        uses: actions/upload-artifact@v3
        with:
          name: creditcoin-fork.json
          path: creditcoin-fork.json

      - name: Upload last block info
        uses: actions/upload-artifact@v3
        with:
          name: last-block-info
          path: "last-block*"
          if-no-files-found: error

  execute-integration-tests:
    needs:
      - fork-creditcoin
      - deploy-github-runner
    runs-on:
      [self-hosted, "${{ needs.deploy-github-runner.outputs.runner_vm_name }}"]
    steps:
      - uses: actions/checkout@v3

      - name: Download creditcoin-node
        uses: actions/download-artifact@v3
        with:
          name: creditcoin-node

      - name: Download creditcoin-fork.json
        uses: actions/download-artifact@v3
        with:
          name: creditcoin-fork.json

      - name: Start a local creditcoin-node from the fork
        run: |
          chmod a+x ./creditcoin-node
          echo "DEBUG: **** free memory before running creditcoin-node ****"
          free -m
          ps aux --sort=-%mem | head -n 20
          echo "DEBUG: *********************"
          ./creditcoin-node --chain ./creditcoin-fork.json --validator \
                            --mining-key 5DkPYq8hFiCeGxFBkz6DAwnTrvKevAJfTYrzFtr9hpDsEAU1 \
                            --monitor-nonce auto >~/creditcoin-node.log 2>&1 &

      - name: Install Docker engine
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || echo
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Start local Ethereum node
        run: |
          sudo docker run --rm -p 8545:8545 -d gluwa/hardhat-dev

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g yarn

      - name: Prepare for integration tests
        run: |
          pushd integration-tests/

          # wait for creditcoin-node to initialize
          ./yarn-install-and-wait-for-creditcoin.sh
          git checkout yarn.lock

          popd

      - name: Configure rustc version
        run: |
          source ci/env
          echo "RUSTC_VERSION=$RUSTC_VERSION" >> "$GITHUB_ENV"
          sudo apt install -y gcc

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          profile: minimal
          override: true

      - name: Install Subwasm
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked --git https://github.com/chevdor/subwasm --tag v0.17.1

      - name: Download WASM runtime
        id: download-wasm
        uses: actions/download-artifact@v3
        with:
          name: creditcoin_node_runtime.compact.compressed.wasm

      - name: Upgrade WASM
        run: |
          yarn --cwd ./scripts/js upgrade 'creditcoin-js'
          echo "DEBUG: **** free memory before runtimeUpgrade ****"
          free -m
          ps aux --sort=-%mem | head -n 20
          echo "DEBUG: *********************"
          yarn --cwd ./scripts/js runtimeUpgrade ws://127.0.0.1:9944 ../../creditcoin_node_runtime.compact.compressed.wasm //Alice 0

      # TODO: wait & confirm wasm upgrade has finished, incl. migrations
      - name: Execute integration tests
        run: |
          echo "DEBUG: **** free memory before running integration tests ****"
          free -m
          ps aux --sort=-%mem | head -n 20
          echo "DEBUG: *********************"
          yarn --cwd ./integration-tests/ test --config creditcoin-fork.config.ts

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: logs
          path: ~/creditcoin-node.log

      - name: Kill creditcoin-node
        run: |
          # if all went well kill the node. Otherwise GitHub Actions would exit on the
          # previous step killing everything and we don't have to worry about
          # dangling processes
          killall -9 creditcoin-node

  deploy-github-runner:
    runs-on: ubuntu-22.04
    needs: setup
    outputs:
      runner_vm_name: ${{ steps.get-env.outputs.runner_vm_name }}
      resource_group: ${{ steps.get-env.outputs.resource_group }}

    steps:
      - uses: actions/checkout@v3

      - name: Install azure-cli
        run: |
          sudo apt remove azure-cli -y && sudo apt autoremove -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          sudo apt install -y jq
          az version

      - name: Authorize hosted-runner
        run: |
          mkdir -p ~/.ssh/
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub >> .github/authorized_keys

      - name: Evaluate env vars
        id: get-env
        run: |
          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "runner_vm_name=${{ env.RUNNER_VM_NAME }}" >> "$GITHUB_OUTPUT"
          echo "resource_group=${{ env.RESOURCE_GROUP }}" >> "$GITHUB_OUTPUT"

      - name: Provision VM
        if: env.LC_GITHUB_REPO_ADMIN_TOKEN
        run: |
          echo "INFO: From ENVs: RUNNER_VM_NAME=${{ env.RUNNER_VM_NAME }}"
          echo "INFO: From Step: RUNNER_VM_NAME=${{ steps.get-env.outputs.runner_vm_name }}"

          az login --service-principal --username "${{ secrets.AZURE_APP_ID }}" --password "${{ secrets.AZURE_APP_PASSWORD }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
          az account set --subscription "Playground Subscription"
          ## az account set -s "${{ secrets.AZURE_SUBSCRIPTION_ID }}"


          # create resource group
          echo "INFO: ${{ steps.get-env.outputs.resource_group }}"
          az group create -n "${{ steps.get-env.outputs.resource_group }}" --location "${{ env.AZ_LOCATION }}"

          # RG Creditcoin-Test is in WestUS and the CPU quota is already full
          # that's why specify a different region here
          az deployment group create -g "${{ steps.get-env.outputs.resource_group }}" -f .github/runner.bicep \
              --parameters location="${{ env.AZ_LOCATION }}" \
              --parameters vmName="${{ steps.get-env.outputs.runner_vm_name }}" \
              --parameters adminPasswordOrKey="$(cat .github/authorized_keys)" > output.json

          # provision the GitHub Runner binary on the VM
          # passing additional ENV values
          SSH_USER_AT_HOSTNAME=$(jq -r '.properties.outputs.sshUserAtHostname.value' < output.json)
          echo "INFO: $SSH_USER_AT_HOSTNAME"

          export LC_RUNNER_VM_NAME="${{ env.RUNNER_VM_NAME }}"
          ssh -i ~/.ssh/id_rsa \
              -o SendEnv=LC_GITHUB_REPO_ADMIN_TOKEN,LC_RUNNER_VM_NAME \
              -o StrictHostKeyChecking=no "$SSH_USER_AT_HOSTNAME" < ./scripts/provision-github-runner.sh
        env:
          LC_GITHUB_REPO_ADMIN_TOKEN: ${{ secrets.GH_REPO_ADMIN_TOKEN }}
          LC_RUNNER_EPHEMERAL: false

  test-migrations-via-try-runtime:
    # see https://gist.github.com/jonico/a94d03cac7a858e0613926d9f1bc7f2b
    runs-on:
      [self-hosted, "${{ needs.deploy-github-runner.outputs.runner_vm_name }}"]
    needs:
      - deploy-github-runner
    steps:
      - uses: actions/checkout@v3

      - name: Download creditcoin-node binary
        uses: actions/download-artifact@v3
        with:
          name: creditcoin-node
          path: target/release

      - name: Download WASM runtime
        uses: actions/download-artifact@v3
        with:
          name: creditcoin_node_runtime.compact.compressed.wasm
          path: target/release

      - name: Restore executable permissions
        run: |
          chmod a+x ./target/release/creditcoin-node

      - name: Check if runner machine meets chain's requirements
        continue-on-error: true
        run: |
          ./scripts/check-hardware.sh

      - name: Testnet ENV
        id: testnet-env
        if: github.base_ref == 'testnet'
        run: |
          echo "rpc_url=wss://rpc.testnet.creditcoin.network:443/ws" >> "$GITHUB_OUTPUT"

      - name: Mainnet ENV
        id: mainnet-env
        if: github.base_ref == 'main'
        run: |
          echo "rpc_url=wss://rpc.mainnet.creditcoin.network:443/ws" >> "$GITHUB_OUTPUT"

      - name: Try-runtime migrations
        run: |
          ./target/release/creditcoin-node try-runtime \
              --runtime ./target/release/creditcoin_node_runtime.compact.compressed.wasm \
              --dev on-runtime-upgrade live --uri ${{ env.RPC_URL }}
        env:
          RPC_URL: ${{ steps.testnet-env.outputs.rpc_url || steps.mainnet-env.outputs.rpc_url }}

  remove-github-runner:
    runs-on: ubuntu-22.04
    needs:
      - deploy-github-runner
      - test-migrations-via-try-runtime
      - execute-integration-tests
    if: ${{ always() && needs.deploy-github-runner.result != 'skipped' }}

    steps:
      - uses: actions/checkout@v3

      - name: Evaluate env vars
        id: get-env
        run: |
          # WARNING: using env.RUNNER_VM_NAME directly in job outputs above
          # doesn't evaluate the $GITHUB_RUN_ID reference
          echo "resource_group=${{ env.RESOURCE_GROUP }}" >> "$GITHUB_OUTPUT"

      - name: Install azure-cli
        run: |
          sudo apt remove azure-cli -y && sudo apt autoremove -y
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      - name: Remove VM
        run: |
          echo "INFO: RUNNER_VM_NAME=${{ env.RUNNER_VM_NAME }}"

          az login --service-principal --username "${{ secrets.AZURE_APP_ID }}" --password "${{ secrets.AZURE_APP_PASSWORD }}" --tenant "${{ secrets.AZURE_TENANT_ID }}"
          az account set --subscription "Playground Subscription"
          az group delete --yes -n "${{ steps.get-env.outputs.resource_group }}"

      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: "Azure resources"
          path: azure_resource_list.json
