name: Build WASM Runtime

on:
  push:
    branches: [main, testnet, dev]
  workflow_dispatch:

jobs:
  srtool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: "creditcoin"
          runtime_dir: runtime
          package: creditcoin-node-runtime
          workdir: ${{ github.workspace }}
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
      - name: Archive Runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.chain }}-runtime-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ matrix.chain }}-srtool-digest.json
