name: Version

on:
  pull_request:
    branches: [dev, testnet, main]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if version.rs was modified
        run: |
          ./scripts/check-version.sh "remotes/origin/$GITHUB_BASE_REF" "$GITHUB_SHA"
